---
title: "Multivariate"
author: "Alexis"
date: "10/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, results = "hide", message = F)
options(scientific=T, digits = 3) 
```

Importing and subsetting datafile
```{r}
dat <- data.frame(read.csv('datafile.csv'))
dat$AdoptionSpeed <- factor(dat$AdoptionSpeed, order=T, levels = c(0,1,2,3,4))

dat$Type = as.factor(dat$Type)
dat$Name = as.factor(dat$Name)
dat$Breed1 = as.factor(dat$Breed1)
dat$Breed2 = as.factor(dat$Breed2)
dat$Gender = as.factor(dat$Gender)
dat$Color1 = as.factor(dat$Color1)
dat$Color2 = as.factor(dat$Color2)
dat$Color3 = as.factor(dat$Color3)
dat$MaturitySize = as.factor(dat$MaturitySize)
dat$FurLength = as.factor(dat$FurLength)
dat$Vaccinated = as.factor(dat$Vaccinated)
dat$Dewormed = as.factor(dat$Dewormed)
dat$Sterilized = as.factor(dat$Sterilized)
dat$Health = as.factor(dat$Health)
dat$State = as.factor(dat$State)
```

Dropping less useful values in categorical variables:
MaturitySize: dropping 0 = Not Specified
FurLength: dropping 0 = Not Specified
Health: dropping 0 = Not Specified

```{r}
dat = subset(dat, dat$Quantity == 1)
dat = subset(dat, ! dat$AdoptionSpeed == 4)
summary(dat)
```

Creating Randomized Dependent Variable

```{r}
# Adding random values
dat$ASnum = NaN
dat$ASnum[dat$AdoptionSpeed == 0] = 0
dat$ASnum[dat$AdoptionSpeed == 1] = runif(sum(dat$AdoptionSpeed == 1), 1, 7)
dat$ASnum[dat$AdoptionSpeed == 2] = runif(sum(dat$AdoptionSpeed == 2), 8, 30)
dat$ASnum[dat$AdoptionSpeed == 3] = runif(sum(dat$AdoptionSpeed == 3), 31, 90)
dat$ASnum[dat$AdoptionSpeed == 4] = 100

summary(dat)
```
Dropping Variables:
``` {r}

```

Creating Cat/Dog subsets
```{r}
dogs = subset(dat, dat$Type == 1)
cats = subset(dat, dat$Type == 2)
```


Simple multivariate analysis on Dog
```{r}
Dog_LM_Simple = lm(ASnum ~ )
```

Anova test 
