---
title: "PetFinder Adoption Final Report"
author: "Group 3: Data Torturers (Alexis Kaldany, Sahara Ensley, Yixi Liang, Kaiyuan Liang)"
date: "`r Sys.Date()`"
output: 
  rmdformats::robobook:
  html_document:
    code_folding: hide
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r setup, include=FALSE}
library(ezids)
# knitr::opts_chunk$set(warning = F, results = "markup", message = F)
knitr::opts_chunk$set(warning = F, results = "hide", message = F, echo = F)
options(scientific=T, digits = 3) 
```

```{r}
## Loading data
data = read.csv('datafile.csv',encoding = "UTF-8")

initialrows = nrow(data)

data$AdoptionSpeed <- factor(data$AdoptionSpeed, order=T, levels = c(0,1,2,3,4))

# converting the data types we want - categorical
data$Type = as.factor(data$Type)
data$MaturitySize = as.factor(data$MaturitySize)
data$FurLength = as.factor(data$FurLength)
data$Vaccinated = as.factor(data$Vaccinated)
data$Gender = as.factor(data$Gender)

# Only looking at profiles with 1 animal
data = subset(data, data$Quantity == 1)
data = subset(data, ! data$AdoptionSpeed == 4)

# Only pulling the columns we want to look at

dat = data[c('Type', 'Age', 'Gender', 'MaturitySize', 'FurLength', 'Vaccinated', 'PhotoAmt','VideoAmt', 'AdoptionSpeed')]

#summary(dat)

set.seed(1000)
samp <- sample(2, nrow(dat), replace=TRUE, prob=c(0.7, 0.3))

train <- dat[samp==1, 1:9]
test <- dat[samp==2, 1:9]

typeknn.trainFeatures = dat[samp == 1, c(2:9)]
typeknn.testFeatures = dat[samp == 2, c(2:9)]
typeknn.trainLabel = dat[samp==1, 1]
typeknn.testLabel = dat[samp==2, 1]
```