---
title: "Independent_Variables_EDA"
author: "YixiLiang"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    number_sections: true
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r init, include=FALSE}
# The package "ezids" (EZ Intro to Data Science) includes a lot of the helper functions we developed for the course. 
# Some of the frequently used functions are loadPkg(), xkabledply(), xkablesummary(), uzscale(), etc.
library(ezids)
 
# some of common options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
# knitr::opts_chunk$set(warning = F, results = "markup", message = F)
knitr::opts_chunk$set(warning = F, results = "hide", message = F)
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
# ‘scipen’: integer. A penalty to be applied when deciding to print numeric values in fixed or exponential notation.  Positive values bias towards fixed and negative towards scientific notation: fixed notation will be preferred unless it is more than ‘scipen’ digits wider.
# use scipen=999 to prevent scientific notation at all times
```


## Loading data
```{r}
#dat = read.csv("E:/Users/REX/RstudioProjects/data_torture/chapter_3/pets_test.csv")
dat <- data.frame(read.csv('datafile.csv'))
dat$AdoptionSpeed <- factor(dat$AdoptionSpeed, order=T, levels = c(0,1,2,3,4))
#data = na.omit(dat) #delete na from data set


dat$Type = as.factor(dat$Type)
dat$Name = as.factor(dat$Name)
dat$Breed1 = as.factor(dat$Breed1)
dat$Breed2 = as.factor(dat$Breed2)
dat$Gender = as.factor(dat$Gender)
dat$Color1 = as.factor(dat$Color1)
dat$Color2 = as.factor(dat$Color2)
dat$Color3 = as.factor(dat$Color3)
dat$MaturitySize = as.factor(dat$MaturitySize)
dat$FurLength = as.factor(dat$FurLength)
dat$Vaccinated = as.factor(dat$Vaccinated)
dat$Dewormed = as.factor(dat$Dewormed)
dat$Sterilized = as.factor(dat$Sterilized)
dat$Health = as.factor(dat$Health)
dat$State = as.factor(dat$State)

summary(dat)
```
```{r}
dat = subset(dat, dat$Quantity == 1)
dat = subset(dat, ! dat$AdoptionSpeed == 4)
#summary(dat)
```

```{r}
dat$ASnum = NaN
dat$ASnum[dat$AdoptionSpeed == 0] = 0
dat$ASnum[dat$AdoptionSpeed == 1] = runif(sum(dat$AdoptionSpeed == 1), 1, 7)
dat$ASnum[dat$AdoptionSpeed == 2] = runif(sum(dat$AdoptionSpeed == 2), 8, 30)
dat$ASnum[dat$AdoptionSpeed == 3] = runif(sum(dat$AdoptionSpeed == 3), 31, 90)

#summary(dat)
```


## Chapter 3
```{r histogram of AdoptionSpeed}
loadPkg("ggplot2")
#Histogram
tmpAdoptionSpeed = as.numeric(dat$AdoptionSpeed)
ggplot(data=dat, aes(tmpAdoptionSpeed)) + 
  geom_bar(breaks=seq(0, 4, by=1),
                 col="red",
                 aes(fill=..count..)) +
  labs(title="AdoptionSpeed of pets") + 
  scale_fill_gradient("Count", low="green", high="red")



#Q-Q plot
qqnorm(tmpAdoptionSpeed, main="Q-Q plot of AdoptionSpeed of pets", ylab = "days",col="blue")
qqline(tmpAdoptionSpeed)
```
We transformed AdoptionSpeed to numerical dependent variable ASnum.
```{r ASnum}
ggplot(data=dat, aes(dat$ASnum)) + 
  geom_histogram(breaks=seq(0, 100, by=5),
                 col="red",
                 aes(fill=..count..)) +
  labs(title="ASnum of pets") + 
  scale_fill_gradient("Count", low="green", high="red")

#Q-Q plot
qqnorm(dat$ASnum, main="Q-Q plot of ASnum of pets", ylab = "days",col="blue")
qqline(dat$ASnum)
```

```{r histogram of Fee}
tmpFee = as.numeric(subset(dat$Fee, !is.na(dat$Fee)))
ggplot(data=dat, aes(tmpFee)) + 
  geom_histogram(breaks=seq(0, 500, by=50),
                 col="red",
                 aes(fill=..count..)) +
  labs(title="Fee of pets") + 
  scale_fill_gradient("Count", low="green", high="red")

#Q-Q plot
qqnorm(tmpFee, main="Q-Q plot of Fee of pets", ylab = "fee",col="blue")
qqline(tmpFee)


```
```{r barplot of Cat and Dog}

catDog = subset(dat, dat$Type == "1" | dat$Type == "2")

ggplot(data=catDog, aes(Type)) + 
  geom_bar(breaks=seq(0, 500, by=100),
                 col="red",
                 aes(fill=..count..)) +
  labs(title="Cats and Dogs", x="Dogs and Cats") + 
  scale_x_discrete(labels= c("Dog","Cat"))
```
```{r donut plot}
# Create test data.
data <- data.frame(
  category=c("Dog", "Cat"),
  count=c(nrow(catDog[catDog$Type=="1",]),nrow(catDog[catDog$Type=="2",]))
)
 
# Compute percentages
data$fraction <- data$count / sum(data$count)

# Compute the cumulative percentages (top of each rectangle)
data$ymax <- cumsum(data$fraction)

# Compute the bottom of each rectangle
data$ymin <- c(0, head(data$ymax, n=-1))

# Compute label position
data$labelPosition <- (data$ymax + data$ymin) / 2

# Compute a good label
data$label <- paste0(data$category, ":", data$count)

# Make the plot
ggplot(data, aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=category)) +
  geom_rect() +
  geom_label( x=3.5, aes(y=labelPosition, label=label), size=6) +
  scale_fill_brewer(palette=4) +
  coord_polar(theta="y") +
  xlim(c(2, 4)) +
  theme_void() +
  theme(legend.position = "none")

```
```{r}
dog = nrow(catDog[catDog$Type=="1",])
cat = nrow(catDog[catDog$Type=="2",])
totalamount = dog+cat

percentDog = format(dog/totalamount * 100, digits = 4)
percentCat = format(cat/totalamount * 100, digits = 4)

Prop <- c(dog,cat)
# Prepare a color palette. Here with R color brewer:
library(RColorBrewer)
myPalette <- brewer.pal(11, "RdYlGn") 

# You can change the border of each area with the classical parameters:
pie(Prop , labels = c(paste("Dog: ",percentDog,"%"), paste("Cat: ",percentCat,"%")), border="white", col=myPalette )
```



```{r barplot of PhotoAmt}
tmpPhotoAmt = dat
tmpPhotoAmt$PhotoAmt = as.numeric(tmpPhotoAmt$PhotoAmt)

ggplot(data=tmpPhotoAmt, aes(PhotoAmt)) + 
  geom_histogram(breaks=seq(0, 30, by=2),
                 col="red",
                 aes(fill=..count..)) +
  labs(title="tmpPhotoAmt of pets") + 
  scale_fill_gradient("Count", low="green", high="red")

#Boxplot
ggplot(data = tmpPhotoAmt,aes(y = PhotoAmt))+
  geom_boxplot() + 
  geom_boxplot( colour="orange", fill="#7777cc", outlier.colour="red", outlier.shape=8, outlier.size=4) +
  labs(title="PhotoAmt boxplot using `ggplot`",x="", y = "PhotoAmt")

#Q-Q plot
qqnorm(tmpPhotoAmt$PhotoAmt, main="Q-Q plot of PhotoAmt of pets", ylab = "PhotoAmt",col="blue")
qqline(tmpPhotoAmt$PhotoAmt)
```
```{r barplot of VideoAmt > 0}
tmpVideoAmt = dat
tmpVideoAmt$VideoAmt = as.numeric(tmpVideoAmt$VideoAmt)
#tmpVideoAmt = subset(tmpVideoAmt, tmpVideoAmt$VideoAmt > 0)
```
```{r}
#barplot
ggplot(data=tmpVideoAmt, aes(VideoAmt)) + 
  geom_bar(breaks=seq(0, 5, by=1),
                 col="red",
                 aes(fill=..count..)) +
  labs(title="tmpVideoAmt of pets") + 
  scale_fill_gradient("Count", low="green", high="red")
```
```{r}
#Boxplot
ggplot(data = tmpVideoAmt,aes(y = VideoAmt))+
  geom_boxplot() + 
  geom_boxplot( colour="orange", fill="#7777cc", outlier.colour="red", outlier.shape=8, outlier.size=4) +
  labs(title="VideoAmt boxplot using `ggplot`",x="", y = "VideoAmt")

#Q-Q plot
qqnorm(tmpVideoAmt$VideoAmt, main="Q-Q plot of VideoAmt of pets", ylab = "VideoAmt",col="blue")
qqline(tmpVideoAmt$VideoAmt)
```

```{r Age}
tmpDatAge = dat
tmpDatAge$Age = as.numeric(dat$Age)

ggplot(data=tmpDatAge, aes(Age)) + 
  geom_histogram(breaks=seq(0, 220, by=10),
                 col="red",
                 aes(fill=..count..)) +
  labs(title="tmpPhotoAmt of pets") + 
  scale_fill_gradient("Count", low="green", high="red")
#Boxplot
ggplot(data = tmpDatAge,aes(y = Age))+
  geom_boxplot() + 
  geom_boxplot( colour="orange", fill="#7777cc", outlier.colour="red", outlier.shape=8, outlier.size=4) +
  labs(title="Age boxplot using `ggplot`",x="", y = "Age")

#Q-Q plot
qqnorm(tmpDatAge$Age, main="Q-Q plot of Age of pets", ylab = "Age",col="blue")
qqline(tmpDatAge$Age)
```
```{r GENDER}
tmpGender = subset(dat, dat$Gender == "1" | dat$Gender == "2")
str(tmpGender$Gender)
```
```{r}
#pie plot
male = nrow(tmpGender[tmpGender$Gender=="1",])
female = nrow(tmpGender[tmpGender$Gender=="2",])
percentMale = format(male/(male+female) * 100, digits = 4)
percentFemale = format(female/(male+female) * 100, digits = 4)
Prop <- c(male,female)
# Prepare a color palette. Here with R color brewer:
library(RColorBrewer)
myPalette <- brewer.pal(3, "Pastel1") 

# You can change the border of each area with the classical parameters:
pie(Prop , labels = c(paste("Male: ", percentMale,"%"),paste("Female: ",percentFemale,"%")), border="white", col=myPalette )
```
```{r donut plot for Gender}
# Create test data.
data <- data.frame(
  category=c("Male", "Female"),
  count=c(nrow(tmpGender[tmpGender$Gender=="1",]),nrow(tmpGender[tmpGender$Gender=="2",]))
)
 
# Compute percentages
data$fraction <- data$count / sum(data$count)

# Compute the cumulative percentages (top of each rectangle)
data$ymax <- cumsum(data$fraction)

# Compute the bottom of each rectangle
data$ymin <- c(0, head(data$ymax, n=-1))

# Compute label position
data$labelPosition <- (data$ymax + data$ymin) / 2

# Compute a good label
data$label <- paste0(data$category, ":", data$count)

# Make the plot
ggplot(data, aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=category)) +
  geom_rect() +
  geom_label( x=3.5, aes(y=labelPosition, label=label), size=6) +
  scale_fill_brewer(palette=9) +
  coord_polar(theta="y") +
  xlim(c(2, 4)) +
  theme_void() +
  theme(legend.position = "none")
```
```{r MaturitySize}
tmpMaturitySize = subset(dat, dat$MaturitySize == "1" | dat$MaturitySize == "2" | dat$MaturitySize == "3" | dat$MaturitySize == "4" )
small = nrow(tmpMaturitySize[tmpMaturitySize$MaturitySize=="1",])
medium = nrow(tmpMaturitySize[tmpMaturitySize$MaturitySize=="2",])
large = nrow(tmpMaturitySize[tmpMaturitySize$MaturitySize=="3",])
extraLarge = nrow(tmpMaturitySize[tmpMaturitySize$MaturitySize=="4",])
totalamount = small+medium+large+extraLarge

percentSmall = format(small/totalamount * 100, digits = 4)
percentMedium = format(medium/totalamount * 100, digits = 4)
percentLarge = format(large/totalamount * 100, digits = 4)
percentExtraLarge = format(extraLarge/totalamount * 100, digits = 4)
#pie plot
Prop <- c(small,medium,large,extraLarge)
# Prepare a color palette. Here with R color brewer:
library(RColorBrewer)
myPalette <- brewer.pal(8, "Spectral") 

# You can change the border of each area with the classical parameters:
pie(Prop , labels = c(paste("Small: ",percentSmall,"%"), paste("Medium: ",percentMedium,"%"), paste("Large: ",percentLarge,"%"), paste("Extra Large: ",percentExtraLarge,"%")), border="white", col=myPalette )

```
```{r donut plot for MaturitySize}
# Create test data.
data <- data.frame(
  category=c("Small", "Medium", "Large", "Extra Large"),
  count=c(nrow(tmpMaturitySize[tmpMaturitySize$MaturitySize=="1",]),nrow(tmpMaturitySize[tmpMaturitySize$MaturitySize=="2",]),
          nrow(tmpMaturitySize[tmpMaturitySize$MaturitySize=="3",]),nrow(tmpMaturitySize[tmpMaturitySize$MaturitySize=="4",]))
)
 
# Compute percentages
data$fraction <- data$count / sum(data$count)

# Compute the cumulative percentages (top of each rectangle)
data$ymax <- cumsum(data$fraction)

# Compute the bottom of each rectangle
data$ymin <- c(0, head(data$ymax, n=-1))

# Compute label position
data$labelPosition <- (data$ymax + data$ymin) / 2

# Compute a good label
data$label <- paste0(data$category, ":", data$count)

# Make the plot
ggplot(data, aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=category)) +
  geom_rect() +
  geom_label( x=3.5, aes(y=labelPosition, label=label), size=6) +
  scale_fill_brewer(palette=9) +
  coord_polar(theta="y") +
  xlim(c(2, 4)) +
  theme_void() +
  theme(legend.position = "none")
```
```{r FurLength }
tmpFurLength  = subset(dat, dat$FurLength == "1"|dat$FurLength == "2"|dat$FurLength == "3")
short = nrow(tmpFurLength[tmpFurLength$FurLength=="1",])
medium = nrow(tmpFurLength[tmpFurLength$FurLength=="2",])
long = nrow(tmpFurLength[tmpFurLength$FurLength=="3",])
totalamount = short+medium+long

percentShort = format(short/totalamount * 100, digits = 4)
percentMedium = format(medium/totalamount * 100, digits = 4)
percentLong = format(long/totalamount * 100, digits = 4)


#pie plot
Prop <- c(short,medium,long)
# Prepare a color palette. Here with R color brewer:
library(RColorBrewer)
myPalette <- brewer.pal(3, "Set2") 

# You can change the border of each area with the classical parameters:
pie(Prop , labels = c(paste("Short: ",percentShort,"%"), paste("Medium: ",percentMedium,"%"), paste("Long: ", percentLong,"%")), border="white", col=myPalette )
```
```{r Vaccinated }
tmpVaccinated = subset(dat, dat$Vaccinated == "1" | dat$Vaccinated == "2" | dat$Vaccinated == "3")
vaccinatedYes = nrow(tmpVaccinated[tmpVaccinated$Vaccinated=="1",])
vaccinatedNo = nrow(tmpVaccinated[tmpVaccinated$Vaccinated=="2",])
vaccinatedNotSure = nrow(tmpVaccinated[tmpVaccinated$Vaccinated=="3",])
totalamount = vaccinatedYes+vaccinatedNo+vaccinatedNotSure

percentVaccinatedYes = format(vaccinatedYes/totalamount * 100, digits = 4)
percentVaccinatedNo = format(vaccinatedNo/totalamount * 100, digits = 4)
percentVaccinatedNotSure = format(vaccinatedNotSure/totalamount * 100, digits = 4)

#pie plot
Prop <- c(vaccinatedYes,vaccinatedNo,vaccinatedNotSure)
# Prepare a color palette. Here with R color brewer:
library(RColorBrewer)
myPalette <- brewer.pal(11,"Paired") 

# You can change the border of each area with the classical parameters:
pie(Prop , labels = c(paste("Vaccinated: ",percentVaccinatedYes, "%"), paste("Unvaccinated: ",percentVaccinatedNo, "%"), paste("Not Specified: ",percentVaccinatedNotSure, "%")), border="white", col=myPalette )

```

